<a href="https://colab.research.google.com/github/RoneyPasolini/EBAC-ColetaDeDados/blob/develop/Profiss%C3%A3o_Analista_de_dados_M20_Exercicio_Roney_Pasolini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Matemática
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Vetorização;</li>
  <li>Arrays Numpy;</li>
  <li>Operações.</li>
</ol>

---

# **Exercícios**

## 1\. Tráfego de São Paulo

Neste exercício, vamos analisar dados de mobilidade urbana da cidade de São Paulo. A base de dados está neste [link](https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv) e é uma copia do dado original, presente neste [link](https://archive.ics.uci.edu/ml/datasets/Behavior+of+the+urban+traffic+of+the+city+of+Sao+Paulo+in+Brazil). A base de dados contem a quantidade de acidentes ocorridos na cidade entre 14/12/09 e 18/12/09, das 07:00h ás 20:00h, agregados em intervalos de 30 minutos.

In [1]:
!wget -q "https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv" -O traffic.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('traffic.csv', sep=';')

In [4]:
df.head()

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,1"
1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,6"
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,7"
3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,2"
4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"11,1"

- **Exemplo**:

O código abaixo extrai a 13ª linha do arquivo que representa a 14ª meia hora do dia 14/12/09, contadas a partir das 07:00h, ou seja, todos os incidentes ocorridos na cidade no dia em questão entre as 13:30h e 14:00h. Vemos, por exemplo, que dois ônibus e dois caminhões ficaram paradados nas ruas da cidade, atrapalhando o tráfego.

In [5]:
df.iloc[[13]]

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
13,14,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,"4,9"

### **1.1. Nativo**

Neste primeira atividade, você deve ler o código abaixo implementado em Python nativo e responder a seguinte pergunta:

> O que o código abaixo computa?

**Resposta**: O código abaixo computa os valores de todos os incidentes que aconteceram em determinado dia.

## Explicação do código

Primeiro ele lê o arquivo, e salva todas os dados na variavel data.
Ele configura as variaveis dia como 14 (pois é o dia em que os dados começaram a ser projetados) e incidents como 0. Cria um dicionario vazio com o nome Incidente_by_day.

No for principal ele trata cada linha do csv de forma separada (cada loop é uma linha)

Em cada loop principal, ele separa os valores das linhas em uma lista chamada timebox_data. Após a separaçaõ, ele cria um loop secundario para somar cada um dos dadaos da linha, para ir somento o numero de incidentes na variavel incidents.

Após realizar a somatoria de incidentes de uma linha, ele captura o valor da primeira coluna, que se refere a hora. cuja o valor varia entre 1 e 27. (Devido a como o csv foi configurado, ele computa um valor inteiro a cada 30 minutos. Lembrando que os dados foram capturados de 07 as 20, o que resulta em 26 horarios. **IMPORTANTE: A hora é computada a partir de 1, devido a isso o valor maximo é 27**)

Caso o valor seja 27, ele salva o numero do dia e o numero de incidentess no dicionario, aumenta o contador de dia em 1 e retorna o valor de incidentes para 0. Recomeçando o loop principal

### Explicação da saida

O código imprime todo o dicionario de incident_by_day

In [6]:
# -- read

data = None

with open(file='traffic.csv', mode='r', encoding='utf8') as fp:

  fp.readline()
  data = fp.read()
  #print(data)

# -- analytics

day = 14
incidents = 0
incident_by_day = dict()

print(data.split(sep='\n')[14])

for timebox in data.split(sep='\n'): # Esta separando os dados de cada linha do csv

  timebox_data = timebox.split(sep=';') # Está separando os dados de cada linha

  # --
  # -- inicio da computação escalar
  # --

  for incident in timebox_data[1: len(timebox_data)-1]: # Esta verificando a existencia de valores acima de 0. Ignorando a primeira coluna (hora).
    incidents = incidents + int(incident)
    #print(incident)
  # --
  # -- fim da computação escalar
  # --

  try:

    half_hour = int(timebox_data[0]) #Captura o valor da hora e verifica se é 27. Correspondendo ao ultimo horario de um dia, se for elle soma o dia e reseta o numero de incidentes para uma nova contagem.

    if half_hour == 27:
      incident_by_day[day] = incidents # Savla os valores de dia e numero de incidentes em um dicionario python
      day = day + 1
      incidents = 0

  except ValueError:
    continue

# -- results

for day in incident_by_day:

  print(f'{day}: {incident_by_day[day]}')

14: 16
15: 63
16: 94
17: 82
18: 85

### **1.2. NumPy**

Substitua o trecho do código do algoritmo que utiliza da **computação escalar** por um que utiliza da **computação vetorial**. Use o pacote NumPy.

In [55]:
# -- read

data = None

with open(file='traffic.csv', mode='r', encoding='utf8') as fp:

  fp.readline()
  data = fp.read()

  #print(data)

# -- analytics

import numpy as np

day = 14
incidents = 0
incident_by_day = dict()

ONE_VALUE = np.ones(16, dtype=int)

for timebox in data.split(sep='\n')[0:-1]: #Verificado que o CSV possui uma linha adicional em branco

  timebox_data = timebox.split(sep=';')


  timebox_array = np.array(timebox_data[1:-1] , dtype=int)

  # --
  # -- inicio da computação vetorial
  # --


  incidents = incidents + np.dot(timebox_array , ONE_VALUE)

  # --
  # -- fim da computação vetorial
  # --

  try:

    half_hour = int(timebox_data[0])

    if half_hour == 27:
      incident_by_day[day] = incidents
      day = day + 1
      incidents = 0

  except ValueError:
    continue

# -- results


for day in incident_by_day:

  print(f'{day}: {incident_by_day[day]}')

14: 16
15: 63
16: 94
17: 82
18: 85

## Observações sobre o execicio:

* Na linha  for timebox in data.split(sep='\n')[0:-1]:. Eu precisei adicionar o limitador [0:-1] pois eu verifiquei que no CSV possui uma linha em branco. Com esse comando, eu consigo ignorar essa falha no arquivo. Mas caberia a proposta de realizar um tratamento de excessão para evitar esses tipos de erros em um cenario real.

* Realizei a transformação de todos os dados que coloquei nos Arrays ONE_VALUE e timebox_array para int, para fazer o código se tornar mais performatico

* Realizei o a criação do ONE_VALUES como uma lista constante de valores 1 para realizar o procedimento de algebra vetorial para somar os incidentes

---